Issue 415: fixed and updated pre-commit hook (#482)
* add i-all script

* add .githooks dir

* update readme with git hook info

* add pretty

* add comments and build

* more consistent message

* move to dev env setup

* update hook to also print to stdout

* better formatting

* update printing

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,33 +1,38 @@
 #!/bin/sh
 
-echo "Running pre-commit hook..."
+formatted_print() {
+  printf "\n%s" "##############################################################################"
+  printf "\n%s" "# > pre-commit: $1"
+  printf "\n%s" "##############################################################################"
+}
 
-# echo "Prettifying Code..."
-# npm run pretty
+# run pretty
+formatted_print "Prettifying Code"
+npm run pretty
 
-# echo "Installing Dependencies..."
-# npm run i-all
+# checking if npm install throws any errors or warnings
+formatted_print "Installing Dependencies"
+if npm run i-all | tee /dev/tty | grep -e 'npm WARN' -e 'npm ERR' > /dev/null; then
+  formatted_print "Commit failed during install" > /dev/stderr
+  exit 1
+fi
 
-# echo "Running Unit Tests..."
-# npm run test
+# checking for failed unit tests
+formatted_print "Running Unit Tests"
+TEST_OUTPUT=$(npm run coverage)
+GREP_OUTPUT=$(echo "$TEST_OUTPUT" | tee /dev/tty | grep failing) > /dev/null
+if [[ -n "$GREP_OUTPUT" ]]; then
+  formatted_print "Failing unit test(s) found"
+  echo "$TEST_OUTPUT" | awk '/'"$GREP_OUTPUT"'/ {flag=1;next} /----------------------------|---------|----------|---------|---------|-------------------/ {flag=0} flag {print}'
+  formatted_print "Commit failed during unit tests" > /dev/stderr
+  exit 1
+fi
 
-# echo "Running Build..."
-# cd client && npm run build
+# check for failing build
+formatted_print Running Build
+if ! npm run pre-commit-build | tee /dev/tty | grep 'Compiled successfully.' > /dev/null; then
+  formatted_print "Commit failed on build" > /dev/stderr
+  exit 1
+fi
 
-# # checking for failed unit tests
-# TEST_OUTPUT=$(npm run coverage)
-# GREP_OUTPUT=$(echo "$TEST_OUTPUT" | grep failing) >/dev/null
-# if [[ -n "$GREP_OUTPUT" ]]; then
-#   echo "Failing unit test(s) found"
-#   echo "$TEST_OUTPUT" | awk '/'"$GREP_OUTPUT"'/ {flag=1;next} /----------------------------|---------|----------|---------|---------|-------------------/ {flag=0} flag {print}'
-#   echo "Commit failed during unit tests" >> /dev/stderr
-#   exit 1
-# fi
-
-# # check for failing build
-# if ! npm run build | grep 'Compiled successfully.' >/dev/null; then
-#   echo "Commit failed on build" >> /dev/stderr
-#   exit 1
-# fi
-
-echo "Completed successfully"
+formatted_print "pre-commit completed successfully!"
